site_name: Documentação - Classificaçõa Pastagem Santa Catarina
site_author: Guilherme Vaz
theme:
  name: readthedocs
  custom_dir: theme_and_images/

extra_css:
  - stylesheets/extra.css
 
nav:
  - 'Home': 'mds/index.md'
  - 'Ingestão de Dados': 'mds/readme_teste.md'
  - 'Pré-processamento': 'mds/Pré processamento dos dados.md'
  - 'Conversão de estrutura Matricial': 'mds/Conversão de estrutura Matricial.md'
  - 'Hierarquização': 'mds/Hierarquização.md'
  - 'Integração Fundiária e Ambiental': 'mds/Integração Fundiária e Ambiental.md'