site_name: Documentação - Classificação Pastagem Santa Catarina
site_author: Guilherme Vaz
site_url: https://guilhermeramosvaz.github.io/Classificacao-Pastagem-SC/
repo_url: https://github.com/guilhermeramosvaz/Classificacao-Pastagem-SC
repo_name: Classificacao-Pastagem-SC
theme:
  name: readthedocs

extra_css:
  - stylesheets/extra.css
 
nav:
  - 'Home': 'index.md'
  - 'Visão Geral': 'mds/01_visao_geral.md'
  - 'Integração de Dados': 'mds/02_integracao_dados.md'
  - 'Desenho Amostral': 'mds/03_desenho_amostral.md'
  - 'Processamento da Classificação': 'mds/04_processamento_classificacao.md'
  - 'Refinamento': 'mds/05_preparacao_refinamento.md'
  - 'Análise do Mapeamento': 'mds/06_analise_mapeamento.md'
  - 'Avaliação de Acurácia': 'mds/07_avaliacao_acuracia.md'
