site_name: Documentação - Classificação Pastagem Santa Catarina
site_author: Guilherme Vaz
site_url: https://guilhermeramosvaz.github.io/Classificacao-Pastagem-SC/
repo_url: https://github.com/guilhermeramosvaz/Classificacao-Pastagem-SC
repo_name: Classificacao-Pastagem-SC
theme:
  name: readthedocs

extra_css:
  - stylesheets/extra.css
 
nav:
  - 'Home': 'index.md'
  - 'Visão Geral': 'mds/visao_geral.md'
  - 'Integração de Dados': 'mds/integracao_dados.md'
  - 'Desenho Amostral': 'mds/desenho_amostral.md'
  - 'Processamento da Classificação': 'mds/processamento_classificacao.md'
  - 'Refinamento': 'mds/preparacao_refinamento.md'
  - 'Análise do Mapeamento': 'mds/analise_mapeamento.md'
  - 'Avaliação de Acurácia': 'mds/avaliacao_acuracia.md'
  - 'Passo a Passo (Scripts)': 'mds/passo_a_passo.md'
